=== fazendadosoftware/leanix/packages/leanix-core/schema/CustomReportMetadata.json
{
    "$id": "/CustomReportMetadata",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "author": {
            "type": "string"
        },
        "defaultConfig": {
            "additionalProperties": true,
            "properties": {
            },
            "type": "object"
        },
        "description": {
            "type": "string"
        },
        "documentationLink": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "reportId": {
            "type": "string"
        },
        "title": {
            "type": "string"
        },
        "version": {
            "type": "string"
        }
    },
    "type": "object"
}

=== fazendadosoftware/leanix/packages/custom-report-vite-demo/lxreport.json
{
  "id": "net.fazendadosoftware.customReportViteDemo",
  "name": "custom-report-vite-demo",
  "title": "LeanIX Custom Report using ViteJS",
  "version": "0.1.0",
  "description": "Demo project for a custom report using ViteJS and the vite-plugin-leanix",
  "author": "Paulo dos Santos",
  "documentationLink": "https://github.com/fazendadosoftware/leanix",
  "defaultConfig": {}
}
